-- =============================================================================
-- Iarah — seed do catálogo (gerado de src/data/catalog.json)
-- Rode DEPOIS de 0001..0006. Idempotente. Migra bancos já populados:
-- renomeia categorias antigas, insere a nova árvore, remapeia produtos e
-- depois apaga as antigas.
-- =============================================================================

-- 1. libera os slugs das categorias antigas que não estão na nova árvore
update public.categories
  set slug = slug || '__legacy'
  where id not in ('ca700000-0000-4000-8000-000000000010', 'ca700000-0000-4000-8000-000000000011', 'ca700000-0000-4000-8000-000000000012', 'ca700000-0000-4000-8000-000000000020', 'ca700000-0000-4000-8000-000000000021', 'ca700000-0000-4000-8000-000000000022', 'ca700000-0000-4000-8000-000000000023', 'ca700000-0000-4000-8000-000000000024', 'ca700000-0000-4000-8000-000000000025', 'ca700000-0000-4000-8000-000000000026') and slug not like '%\_\_legacy';

-- 2. insere/atualiza a nova árvore (raízes antes das subcategorias, por FK)
insert into public.categories (id, slug, name, description, position, image_url, parent_id) values
  ('ca700000-0000-4000-8000-000000000010', 'rosto', 'Rosto', 'Tudo para o cuidado facial, do primeiro passo ao último.', 1, '', null),
  ('ca700000-0000-4000-8000-000000000011', 'corpo', 'Corpo', 'Proteção e hidratação para o corpo todo.', 2, '', null),
  ('ca700000-0000-4000-8000-000000000012', 'kits', 'Kits', 'Rotinas completas montadas para começar sem erro.', 3, '', null),
  ('ca700000-0000-4000-8000-000000000020', 'limpeza-facial', 'Limpeza facial', 'Retirar o dia sem tirar a água da pele.', 1, '', 'ca700000-0000-4000-8000-000000000010'),
  ('ca700000-0000-4000-8000-000000000021', 'hidratacao', 'Hidratação', 'Camadas leves que devolvem à pele o que a rotina evapora.', 2, '', 'ca700000-0000-4000-8000-000000000010'),
  ('ca700000-0000-4000-8000-000000000022', 'protetor-solar', 'Proteção solar facial', 'Proteção diária de toque seco — o passo que não se pula.', 3, '', 'ca700000-0000-4000-8000-000000000010'),
  ('ca700000-0000-4000-8000-000000000023', 'seruns-tratamento', 'Séruns & tratamento', 'Ativos concentrados para objetivos específicos.', 4, '', 'ca700000-0000-4000-8000-000000000010'),
  ('ca700000-0000-4000-8000-000000000024', 'mascaras', 'Máscaras', 'Pausas semanais de imersão para a pele respirar.', 5, '', 'ca700000-0000-4000-8000-000000000010'),
  ('ca700000-0000-4000-8000-000000000025', 'protecao-solar-corpo', 'Proteção solar corporal', 'FPS para a pele exposta do corpo.', 1, '', 'ca700000-0000-4000-8000-000000000011'),
  ('ca700000-0000-4000-8000-000000000026', 'rotinas-prontas', 'Rotinas prontas', 'Kits com desconto para começar.', 1, '', 'ca700000-0000-4000-8000-000000000012')
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, description = excluded.description,
  position = excluded.position, image_url = excluded.image_url, parent_id = excluded.parent_id;

-- 3. produtos (category_id já aponta para a subcategoria nova)
insert into public.products
  (id, slug, name, category_id, short_description, description, ingredients, how_to_use,
   price_cents, compare_at_price_cents, stock, is_active, is_bestseller, rating, reviews_count,
   images, attributes)
values
  ('d0000000-0000-4000-8000-000000000001', 'gel-de-limpeza-aguas-claras', 'Gel de Limpeza Águas Claras', 'ca700000-0000-4000-8000-000000000020',
   'Gel translúcido que limpa sem repuxar, com ácido hialurônico e chá verde.', 'Uma limpeza que respeita a barreira da pele. A espuma leve dissolve oleosidade, poluição e resíduos de protetor solar enquanto o ácido hialurônico de baixo peso molecular mantém a hidratação no lugar. O pH levemente ácido (5,5) preserva o manto natural, e o extrato de chá verde acalma a pele sensibilizada pelo dia. Enxágue e a pele fica limpa, macia e sem aquela sensação de aperto.', 'Aqua, Coco-Glucoside, Sodium Cocoyl Isethionate, Glycerin, Sodium Hyaluronate, Camellia Sinensis Leaf Extract, Panthenol, Allantoin, Citric Acid, Sodium Benzoate, Potassium Sorbate', 'De manhã e à noite, aplique uma noz do produto na pele úmida, massageie em movimentos circulares por 30 segundos e enxágue com água morna. À noite, use após o demaquilante.',
   6990, null, 40, true, true,
   4.8, 214, '["https://images.unsplash.com/photo-1556228720-195a672e8a03","https://images.unsplash.com/photo-1617897903246-719242758050"]'::jsonb, '{"skin_types":["oleosa","seca","mista","normal","sensivel"],"concerns":["oleosidade"],"routine_step":"limpeza","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000002', 'oleo-bifasico-demaquilante-fonte', 'Óleo Bifásico Demaquilante Fonte', 'ca700000-0000-4000-8000-000000000020',
   'Fase óleo + fase água que remove maquiagem à prova d''água e protetor solar num gesto.', 'Agite e as duas fases se encontram: os óleos vegetais de girassol e jojoba envolvem a maquiagem à prova d''água e o protetor solar resistente, enquanto a fase aquosa com água de coco arrasta tudo embora. Emulsiona em contato com a água e enxágua limpo, sem véu gorduroso. Ideal como primeiro passo da limpeza dupla à noite.', 'Aqua, Helianthus Annuus Seed Oil, Simmondsia Chinensis Seed Oil, Cocos Nucifera Water, Caprylic/Capric Triglyceride, Dipropylene Glycol, Tocopherol, Parfum', 'Agite bem antes de usar. Com o rosto e as mãos secos, aplique de 4 a 6 gotas e massageie sobre a maquiagem. Adicione um pouco de água para emulsionar e enxágue. Siga com um gel de limpeza.',
   8990, null, 28, true, false,
   4.7, 96, '["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b","https://images.unsplash.com/photo-1612817288484-6f916006741a"]'::jsonb, '{"skin_types":["oleosa","mista","normal","seca"],"concerns":[],"routine_step":"limpeza","time_of_day":"pm","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000003', 'sabonete-facial-argila-rosa', 'Sabonete Facial em Barra Argila Rosa', 'ca700000-0000-4000-8000-000000000020',
   'Barra syndet com argila rosa e óleo de framboesa para peles normais a mistas.', 'Um syndet — sabonete sem sabão — prensado a frio com argila rosa francesa, que limpa a oleosidade da zona T sem agredir as bochechas. O óleo de semente de framboesa repõe lipídios e o glicerol vegetal segura a água na pele. Rende meses e dispensa embalagem plástica.', 'Sodium Cocoyl Isethionate, Kaolin, Cetearyl Alcohol, Glycerin, Rubus Idaeus Seed Oil, Coco-Glucoside, Illite (CI 77004), Tocopherol', 'Espume a barra entre as mãos úmidas e massageie a espuma no rosto por 30 segundos. Enxágue. Deixe a barra secar num saboneteira com drenagem entre os usos.',
   4490, null, 55, true, false,
   4.6, 61, '["https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19"]'::jsonb, '{"skin_types":["oleosa","mista","normal"],"concerns":["oleosidade","poros"],"routine_step":"limpeza","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000004', 'hidratante-facial-veu-de-agua', 'Hidratante Facial Véu de Água', 'ca700000-0000-4000-8000-000000000021',
   'Gel-creme oil-free com niacinamida 4% e ácido hialurônico. Some na pele.', 'A textura water-gel foi feita para o clima brasileiro: entra na pele em segundos, sem peso e sem brilho, e deixa um acabamento aveludado que segura a maquiagem. A niacinamida a 4% regula a oleosidade e uniformiza o tom ao longo das semanas; três pesos de ácido hialurônico hidratam em camadas diferentes da epiderme. Não comedogênico.', 'Aqua, Glycerin, Niacinamide, Dimethicone, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Butylene Glycol, Panthenol, Allantoin, Tocopheryl Acetate, Carbomer, Sodium Hydroxide, Phenoxyethanol, Ethylhexylglycerin', 'De manhã e à noite, após o sérum, aplique uma quantidade equivalente a uma ervilha em todo o rosto e pescoço. De manhã, finalize com protetor solar.',
   9990, null, 37, true, true,
   4.9, 302, '["https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd","https://images.unsplash.com/photo-1602928321679-560bb453f190"]'::jsonb, '{"skin_types":["oleosa","mista","normal"],"concerns":["oleosidade","poros","desidratacao","tom-irregular"],"routine_step":"hidratacao","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000005', 'creme-hidratante-nutritivo-correnteza', 'Creme Hidratante Nutritivo Correnteza', 'ca700000-0000-4000-8000-000000000021',
   'Creme encorpado com ceramidas e manteiga de murumuru para peles secas.', 'Para quando a pele pede mais. A tríade de ceramidas idênticas às da pele reconstrói a barreira, a manteiga amazônica de murumuru repõe lipídios e a glicerina puxa água para dentro. O resultado é uma pele confortável por horas, sem descamação, mesmo no ar-condicionado ou no frio. Fragrância suave de flor de laranjeira.', 'Aqua, Glycerin, Caprylic/Capric Triglyceride, Astrocaryum Murumuru Seed Butter, Cetearyl Alcohol, Ceramide NP, Ceramide AP, Ceramide EOP, Phytosphingosine, Cholesterol, Squalane, Panthenol, Xanthan Gum, Parfum, Phenoxyethanol', 'À noite, como último passo, aqueça uma pequena porção entre os dedos e pressione sobre o rosto e o pescoço. De dia, use em peles muito secas antes do protetor solar.',
   11990, null, 22, true, false,
   4.8, 118, '["https://images.unsplash.com/photo-1631730359585-38a4935cbec4","https://images.unsplash.com/photo-1598440947619-2c35fc9aa908"]'::jsonb, '{"skin_types":["seca","normal","sensivel"],"concerns":["desidratacao","vermelhidao"],"routine_step":"hidratacao","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000006', 'bruma-hidratante-orvalho', 'Bruma Hidratante Orvalho', 'ca700000-0000-4000-8000-000000000021',
   'Névoa fina de água termal e pantenol para refrescar e fixar a maquiagem.', 'Um borrifo de frescor a qualquer hora do dia. A água termal rica em minerais acalma, o pantenol e a betaína hidratam na hora e o acabamento é seco, sem escorrer. Use antes do hidratante para potencializar a absorção, depois da maquiagem para tirar o aspecto de pó, ou no meio da tarde para revitalizar.', 'Aqua (Thermal Spring Water), Panthenol, Betaine, Glycerin, Sodium PCA, Allantoin, Sodium Hyaluronate, Leuconostoc/Radish Root Ferment Filtrate', 'Feche os olhos e borrife a 20 cm do rosto sempre que quiser. Para fixar a maquiagem, aplique após finalizar e deixe secar naturalmente.',
   5990, null, 44, true, false,
   4.7, 87, '["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9","https://images.unsplash.com/photo-1596755389378-c31d21fd1273"]'::jsonb, '{"skin_types":["oleosa","seca","mista","normal","sensivel"],"concerns":["desidratacao","vermelhidao"],"routine_step":"complemento","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000007', 'protetor-solar-facial-fps-60-toque-seco', 'Protetor Solar Facial FPS 60 Toque Seco', 'ca700000-0000-4000-8000-000000000022',
   'FPS 60 / FPS-UVA 20, textura fluida que seca em pó e não deixa cara branca.', 'O protetor que você lembra de repassar porque é gostoso de usar. Filtros modernos garantem proteção alta contra UVA e UVB, a textura fluida espalha fácil e seca num acabamento aveludado que controla o brilho por horas. Sem álcool na fórmula, sem perfume e sem resíduo esbranquiçado, mesmo em peles mais escuras. Resistente à água por 80 minutos.', 'Aqua, Ethylhexyl Methoxycinnamate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Silica, Niacinamide, Dimethicone, Butyl Methoxydibenzoylmethane, Tocopherol, Glycerin, Phenoxyethanol', 'Todas as manhãs, como último passo do skincare, aplique dois dedos de produto no rosto, pescoço e orelhas 15 minutos antes de sair. Reaplique a cada 3 horas de exposição ou após suar ou entrar na água.',
   8990, null, 60, true, true,
   4.9, 411, '["https://images.unsplash.com/photo-1556229174-5e42a09e45af","https://images.unsplash.com/photo-1620916566398-39f1143ab7be"]'::jsonb, '{"skin_types":["oleosa","mista","normal","seca"],"concerns":[],"routine_step":"protecao","time_of_day":"am","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000008', 'protetor-solar-com-cor-fps-50', 'Protetor Solar com Cor FPS 50', 'ca700000-0000-4000-8000-000000000022',
   'Proteção FPS 50 com pigmentos minerais que se adaptam e uniformizam o tom.', 'Cobertura leve e proteção alta no mesmo passo. Os pigmentos de óxido de ferro se ajustam a uma ampla faixa de tons de pele, disfarçam vermelhidão e olheiras e ainda ajudam a barrar a luz visível — aquela que vem das telas e piora o melasma. Acabamento natural, nem matte nem glow, que passa por base nos dias de pressa.', 'Aqua, Ethylhexyl Methoxycinnamate, Titanium Dioxide, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, CI 77491, CI 77492, CI 77499, Niacinamide, Dimethicone, Glycerin, Tocopherol, Phenoxyethanol', 'De manhã, aplique uma quantidade generosa e uniforme sobre o hidratante, esfumando na direção do pescoço. Use sozinho ou como base para a maquiagem. Reaplique ao longo do dia com a versão em pó ou bruma.',
   9490, null, 33, true, false,
   4.7, 158, '["https://images.unsplash.com/photo-1631729371254-42c2892f0e6e","https://images.unsplash.com/photo-1567721913486-6585f069b332"]'::jsonb, '{"skin_types":["oleosa","mista","normal","seca","sensivel"],"concerns":["manchas","tom-irregular"],"routine_step":"protecao","time_of_day":"am","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000009', 'protetor-solar-fluido-corporal-fps-50', 'Protetor Solar Fluido Corporal FPS 50', 'ca700000-0000-4000-8000-000000000025',
   'Loção corporal FPS 50 de rápida absorção, resistente à água, sem pegajosidade.', 'Feito para o corpo todo e para o dia a dia — não só para a praia. A loção fluida espalha rápido numa área grande, absorve sem deixar a pele grudenta e resiste a 80 minutos na água. Enriquecida com aloe vera e vitamina E para hidratar enquanto protege.', 'Aqua, Homosalate, Ethylhexyl Salicylate, Octocrylene, Butyl Methoxydibenzoylmethane, Aloe Barbadensis Leaf Juice, Glycerin, Tocopheryl Acetate, Dimethicone, Cetyl Alcohol, Phenoxyethanol', 'Aplique com generosidade em toda a pele exposta 15 minutos antes da exposição solar. Reaplique a cada 2 horas e sempre após nadar, suar muito ou se secar com a toalha.',
   7990, null, 41, true, false,
   4.6, 73, '["https://images.unsplash.com/photo-1595877244574-e90ce41ce089","https://images.unsplash.com/photo-1556228578-8c89e6adf883"]'::jsonb, '{"skin_types":["oleosa","seca","mista","normal","sensivel"],"concerns":[],"routine_step":"complemento","time_of_day":"am","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000010', 'serum-vitamina-c-15-reflexo', 'Sérum Vitamina C 15% Reflexo', 'ca700000-0000-4000-8000-000000000023',
   'Ácido L-ascórbico 15% com vitamina E e ácido ferúlico para luminosidade e firmeza.', 'A fórmula de antioxidante mais estudada da dermatologia, na concentração que funciona sem irritar. A vitamina C pura neutraliza radicais livres da poluição e do sol, estimula colágeno e clareia manchas ao longo de 8 a 12 semanas. A dupla vitamina E + ácido ferúlico estabiliza a fórmula e multiplica a proteção. Frasco âmbar com conta-gotas para preservar a potência.', 'Aqua, Ascorbic Acid, Propylene Glycol, Ethoxydiglycol, Glycerin, Tocopherol, Ferulic Acid, Panthenol, Sodium Hyaluronate, Triethanolamine', 'De manhã, na pele limpa e seca, aplique de 3 a 4 gotas no rosto e pescoço antes do hidratante. Sempre finalize a rotina da manhã com protetor solar. Introduza em dias alternados nas primeiras duas semanas.',
   14990, null, 26, true, true,
   4.8, 267, '["https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c","https://images.unsplash.com/photo-1608248597279-f99d160bfcbc"]'::jsonb, '{"skin_types":["oleosa","mista","normal"],"concerns":["manchas","tom-irregular","opacidade","linhas-finas"],"routine_step":"tratamento","time_of_day":"am","strength":"moderado","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000011', 'serum-niacinamida-10-zinco', 'Sérum Niacinamida 10% + Zinco', 'ca700000-0000-4000-8000-000000000023',
   'Controla oleosidade, minimiza poros e uniformiza o tom sem ressecar.', 'Um curinga para peles oleosas e mistas. A niacinamida a 10% regula a produção de sebo, reduz a aparência dos poros dilatados e clareia marquinhas de acne; o PCA de zinco reforça o controle de brilho. Textura aquosa que seca rápido e combina bem embaixo do protetor solar. Bem tolerado até por peles sensíveis.', 'Aqua, Niacinamide, Pentylene Glycol, Zinc PCA, Glycerin, Tasmannia Lanceolata Fruit/Leaf Extract, Panthenol, Allantoin, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin', 'De manhã e/ou à noite, aplique de 4 a 5 gotas na pele limpa antes do hidratante. Evite usar na mesma camada que a vitamina C pura — prefira uma no período da manhã e outra à noite.',
   10990, null, 34, true, false,
   4.7, 189, '["https://images.unsplash.com/photo-1612817159949-195b6eb9e31a","https://images.unsplash.com/photo-1571781926291-c477ebfd024b"]'::jsonb, '{"skin_types":["oleosa","mista","sensivel"],"concerns":["oleosidade","poros","acne","tom-irregular","vermelhidao"],"routine_step":"tratamento","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000012', 'serum-acido-hialuronico-2-profundeza', 'Sérum Ácido Hialurônico 2% Profundeza', 'ca700000-0000-4000-8000-000000000023',
   'Cinco pesos moleculares de ácido hialurônico para hidratar em camadas.', 'Hidratação que vai além da superfície. Cinco frações de ácido hialurônico e hialuronato de sódio agem em profundidades diferentes da pele, enquanto o pró-ácido hialurônico estimula a produção natural. A pele fica mais preenchida, com linhas de desidratação suavizadas e um viço imediato. Use sobre a pele levemente úmida para selar ainda mais água.', 'Aqua, Glycerin, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate Crosspolymer, Hyaluronic Acid, Panthenol, Betaine, Pentylene Glycol, Xanthan Gum, Phenoxyethanol', 'De manhã e à noite, aplique de 3 a 4 gotas na pele ainda úmida após a limpeza ou a bruma. Sele com o hidratante em seguida para evitar que a água evapore em ambientes secos.',
   11990, null, 30, true, true,
   4.8, 176, '["https://images.unsplash.com/photo-1615397587950-3cbb55f95b77","https://images.unsplash.com/photo-1627384113743-6bd5a479fffd"]'::jsonb, '{"skin_types":["oleosa","seca","mista","normal","sensivel"],"concerns":["desidratacao","linhas-finas","opacidade"],"routine_step":"tratamento","time_of_day":"ambos","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000013', 'tratamento-noturno-retinal-lua-nova', 'Tratamento Noturno Retinal 0,1% Lua Nova', 'ca700000-0000-4000-8000-000000000023',
   'Retinaldeído encapsulado 0,1% para renovação, linhas finas e textura.', 'O retinal (retinaldeído) age mais rápido que o retinol e costuma incomodar menos. A liberação encapsulada distribui o ativo ao longo da noite, acelerando a renovação celular, suavizando linhas finas, refinando a textura e clareando manchas. A base com esqualano e bisabolol conforta a pele durante a adaptação. Uso exclusivamente noturno.', 'Aqua, Squalane, Caprylic/Capric Triglyceride, Retinal (Retinaldehyde), Glycerin, Bisabolol, Tocopherol, Hydroxyethylcellulose, Panthenol, Phenoxyethanol, Ethylhexylglycerin', 'À noite, comece 2 vezes por semana sobre a pele limpa e totalmente seca, aumentando a frequência conforme a tolerância. Aplique uma ervilha no rosto, aguarde absorver e finalize com hidratante. Protetor solar diário é obrigatório durante o uso.',
   17990, null, 18, true, false,
   4.7, 132, '["https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c","https://images.unsplash.com/photo-1556228453-efd6c1ff04f6"]'::jsonb, '{"skin_types":["normal","mista","seca"],"concerns":["linhas-finas","firmeza","tom-irregular","manchas","acne"],"routine_step":"tratamento","time_of_day":"pm","strength":"potente","pregnancy_safe":false}'::jsonb),
  ('d0000000-0000-4000-8000-000000000014', 'serum-antioxidante-resveratrol-ferulico', 'Sérum Antioxidante Resveratrol + Ácido Ferúlico', 'ca700000-0000-4000-8000-000000000023',
   'Antioxidante noturno com resveratrol 1% e ácido ferúlico 0,5% para defesa e firmeza.', 'Uma alternativa à vitamina C para quem tem pele sensível ou prefere concentrar os antioxidantes à noite. O resveratrol, polifenol da uva, combate o estresse oxidativo acumulado no dia e apoia a firmeza; o ácido ferúlico amplia o efeito e a estabilidade. Textura sérum-óleo seco que absorve sem pesar.', 'Dicaprylyl Carbonate, Resveratrol, Ferulic Acid, Squalane, Caprylic/Capric Triglyceride, Tocopherol, Bisabolol, Helianthus Annuus Seed Oil, Rosmarinus Officinalis Leaf Extract', 'À noite, após os ativos aquosos e antes do hidratante, aqueça de 3 a 4 gotas entre os dedos e pressione sobre o rosto e o pescoço. Pode ser alternado com o tratamento de retinal em noites diferentes.',
   15990, null, 21, true, false,
   4.6, 54, '["https://images.unsplash.com/photo-1573575155376-b5010099301b","https://images.unsplash.com/photo-1608248597279-f99d160bfcbc"]'::jsonb, '{"skin_types":["sensivel","seca","normal","mista"],"concerns":["firmeza","linhas-finas","opacidade"],"routine_step":"tratamento","time_of_day":"pm","strength":"moderado","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000015', 'mascara-facial-hidratante-remanso', 'Máscara Facial Hidratante em Creme Remanso', 'ca700000-0000-4000-8000-000000000024',
   'Máscara-creme com ácido hialurônico, esqualano e mel para reidratar em 10 minutos.', 'Um resgate para a pele cansada, desidratada ou marcada pelo sol e pelo avião. A camada generosa de creme entrega ácido hialurônico, esqualano vegetal e mel — umectante natural — que devolvem maciez e viço. Pode ficar como máscara de dez minutos ou virar máscara noturna em camada fina nos dias mais secos.', 'Aqua, Glycerin, Squalane, Sodium Hyaluronate, Mel (Honey), Butyrospermum Parkii Butter, Panthenol, Allantoin, Cetearyl Alcohol, Tocopheryl Acetate, Xanthan Gum, Phenoxyethanol', 'De 2 a 3 vezes por semana, após a limpeza, aplique uma camada espessa e uniforme evitando a área dos olhos. Deixe agir por 10 a 15 minutos e retire o excesso com um algodão úmido ou massageie o restante na pele. Use à noite.',
   7490, null, 29, true, false,
   4.8, 101, '["https://images.unsplash.com/photo-1596755389378-c31d21fd1273","https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d"]'::jsonb, '{"skin_types":["seca","normal","sensivel"],"concerns":["desidratacao","opacidade"],"routine_step":"complemento","time_of_day":"pm","strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000016', 'mascara-detox-argila-preta-carvao', 'Máscara Detox Argila Preta + Carvão', 'ca700000-0000-4000-8000-000000000024',
   'Argila preta e carvão ativado para descongestionar poros sem ressecar.', 'Para a semana em que a pele deu sinais de sobrecarga. A argila preta absorve o excesso de oleosidade, o carvão ativado captura impurezas dos poros e a niacinamida e o pantenol na fórmula evitam aquele repuxado clássico das máscaras de argila. Sai fácil e deixa a pele fosca, lisa e respirando.', 'Aqua, Kaolin, Bentonite, Charcoal Powder, Glycerin, Niacinamide, Panthenol, Propanediol, Aloe Barbadensis Leaf Juice, Menthol, Xanthan Gum, Phenoxyethanol', 'Uma vez por semana, após a limpeza, aplique uma camada média sobre a zona T ou o rosto todo, evitando os olhos e a boca. Aguarde de 8 a 10 minutos — sem deixar secar por completo — e enxágue com água morna. Siga com sérum e hidratante.',
   6490, null, 32, true, false,
   4.5, 78, '["https://images.unsplash.com/photo-1590439471364-192aa70c0b53","https://images.unsplash.com/photo-1512496015851-a90fb38ba796"]'::jsonb, '{"skin_types":["oleosa","mista"],"concerns":["oleosidade","poros","acne"],"routine_step":"esfoliacao","time_of_day":"pm","strength":"moderado","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000017', 'kit-ritual-essencial', 'Kit Ritual Essencial', 'ca700000-0000-4000-8000-000000000026',
   'Limpeza, hidratação e proteção — os três passos que sustentam qualquer pele.', 'O ponto de partida. Reúne o Gel de Limpeza Águas Claras, o Hidratante Facial Véu de Água e o Protetor Solar Facial FPS 60 Toque Seco numa rotina de manhã e noite que qualquer tipo de pele tolera bem. Acompanha um cartão com a ordem de uso. Economia de R$ 24,80 em relação aos itens avulsos.', 'Contém: Gel de Limpeza Águas Claras (150 ml), Hidratante Facial Véu de Água (50 g), Protetor Solar Facial FPS 60 Toque Seco (50 g). Composição completa nas páginas de cada produto.', 'Manhã: limpar, hidratar, protetor solar. Noite: limpar e hidratar. Um passo de cada vez, todos os dias — consistência importa mais do que quantidade de produtos.',
   22990, 25470, 15, true, true,
   4.9, 143, '["https://images.unsplash.com/photo-1600612253971-422e7f7faeb6","https://images.unsplash.com/photo-1602928321679-560bb453f190"]'::jsonb, '{"skin_types":[],"concerns":[],"routine_step":null,"time_of_day":null,"strength":"suave","pregnancy_safe":true}'::jsonb),
  ('d0000000-0000-4000-8000-000000000018', 'kit-glow-vitamina-c', 'Kit Glow Vitamina C', 'ca700000-0000-4000-8000-000000000026',
   'Rotina de luminosidade: sérum de vitamina C, hidratante e bruma revitalizante.', 'Para quem quer trabalhar manchas e opacidade. Combina o Sérum Vitamina C 15% Reflexo, o Hidratante Facial Véu de Água e a Bruma Hidratante Orvalho numa sequência de manhã que ilumina o tom ao longo de 8 a 12 semanas. Acompanha cartão com a rotina e dicas de introdução. Economia de R$ 39,80.', 'Contém: Sérum Vitamina C 15% Reflexo (30 ml), Hidratante Facial Véu de Água (50 g), Bruma Hidratante Orvalho (100 ml). Composição completa nas páginas de cada produto.', 'Manhã: limpar, borrifar a bruma, aplicar o sérum de vitamina C, hidratar e finalizar com protetor solar (não incluso). Comece o sérum em dias alternados na primeira semana.',
   26990, 30970, 12, true, false,
   4.8, 67, '["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b","https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c"]'::jsonb, '{"skin_types":[],"concerns":[],"routine_step":null,"time_of_day":null,"strength":"suave","pregnancy_safe":true}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  category_id = excluded.category_id,
  short_description = excluded.short_description,
  description = excluded.description,
  ingredients = excluded.ingredients,
  how_to_use = excluded.how_to_use,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  stock = excluded.stock,
  is_active = excluded.is_active,
  is_bestseller = excluded.is_bestseller,
  rating = excluded.rating,
  reviews_count = excluded.reviews_count,
  images = excluded.images,
  attributes = excluded.attributes;

-- 4. remove as categorias antigas (nada mais aponta para elas)
delete from public.categories where slug like '%\_\_legacy';


insert into public.offers
  (id, position, is_active, image_url, eyebrow, title, subtitle, cta_label, cta_href)
values
  ('0ffe0000-0000-4000-8000-000000000001', 1, true, 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1920&q=70', 'Skincare inspirado na água', 'A pele pede menos passos e mais hidratação', 'Fórmulas limpas, textura leve e resultado que você sente ao toque — sem prometer milagre em dez frascos.', 'Ver a loja', '/loja'),
  ('0ffe0000-0000-4000-8000-000000000002', 2, true, 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1920&q=70', 'Não sabe por onde começar?', 'Descubra a sua rotina em 2 minutos', 'Responda 7 perguntas e receba uma rotina de manhã e de noite feita pra sua pele.', 'Fazer o teste de pele', '/rotina')
on conflict (id) do nothing;


insert into public.site_content (section, is_active, data) values
  ('brand', true, '{"logo_url":""}'::jsonb),
  ('home_quiz', true, '{"eyebrow":"Não sabe por onde começar?","title":"Responda 7 perguntas e receba a sua rotina","body":"Montamos um passo a passo de manhã e de noite com produtos Iarah para o seu tipo de pele e seus objetivos — com o porquê de cada um.","cta_label":"Fazer o teste de pele","cta_href":"/rotina"}'::jsonb),
  ('home_bestsellers', true, '{"eyebrow":"Escolhas da casa","title":"Os mais queridos","cta_label":"Ver todos os produtos","cta_href":"/loja"}'::jsonb),
  ('home_story', true, '{"eyebrow":"A história do nome","title":"Iara cuidava dos rios.\nA gente cuida da barreira da pele.","body":"No folclore brasileiro, Iara é a mãe d''água — protege as fontes e mantém o equilíbrio dos rios. É essa a lógica das nossas fórmulas: repor água, selar o que já existe e não agredir o que funciona. Menos ativos gritando, mais hidratação constante.","cta_label":"Conhecer a marca","cta_href":"/sobre","features":[{"title":"Fórmulas curtas","body":"Sem listas de 40 ingredientes. Cada item tem função."},{"title":"Testado dermatologicamente","body":"Todos os produtos passam por teste de irritabilidade."},{"title":"Cruelty-free","body":"Não testamos em animais em nenhuma etapa."},{"title":"Feito no Brasil","body":"Produção nacional, para o clima e a pele daqui."}]}'::jsonb),
  ('home_social', true, '{"eyebrow":"Quem já usa","title":"Mais de 12 mil peles cuidadas","subtitle":"Avaliação média 4,8 / 5 em 2.1 mil comentários","testimonials":[{"quote":"Minha pele estava desidratada de tanto ácido. Em três semanas com o sérum de hialurônico e o Véu de Água ela voltou a parecer viva.","name":"Marina R.","detail":"pele mista, São Paulo"},{"quote":"O protetor de toque seco é o único que consigo reaplicar no trabalho sem ficar oleosa. Virou item fixo da nécessaire.","name":"Letícia F.","detail":"pele oleosa, Recife"},{"quote":"Comprei o Kit Ritual Essencial pra minha mãe e acabei roubando. Rotina simples, sem dez passos, e funciona.","name":"Carolina M.","detail":"pele normal, Curitiba"}]}'::jsonb),
  ('footer', true, '{"tagline":"Cuidados com a pele inspirados na água — fórmulas simples, hidratação de verdade.","returns_line":"Trocas em até 7 dias corridos.","legal_line":"Iarah Cosméticos. CNPJ 00.000.000/0001-00. Todos os direitos reservados.","payment_line":"Pagamentos processados pelo Mercado Pago · Pix e cartão em até 6x"}'::jsonb),
  ('contact', true, '{"email":"ola@iarah.com.br","whatsapp_number":"","hours":"Segunda a sexta, das 9h às 18h"}'::jsonb),
  ('page_sobre', true, '{"hero_eyebrow":"Nossa história","hero_title":"Cuidar da pele como\nquem cuida de uma nascente","paragraphs":["Iara é a mãe d''água do folclore brasileiro — a figura que protege os rios e mantém o equilíbrio das águas. Quando pensamos no nome da marca, era essa imagem que queríamos: cuidado paciente, constante, sem violência.","A Iarah nasceu da frustração com rotinas de skincare de dez passos que prometem tudo e irritam a pele. Nosso ponto de partida foi o oposto: fórmulas curtas, ativos em concentrações que a literatura sustenta e um compromisso com a barreira cutânea — porque pele saudável é pele hidratada.","Trabalhamos com a lógica da estética coreana (camadas leves, texturas que somem, proteção solar como prioridade), mas formulamos para o clima e a pele brasileiros, com produção nacional."],"values":[{"title":"Água primeiro","body":"Cada fórmula começa pela pergunta: isso ajuda a pele a reter água? Se não, não entra."},{"title":"Transparência","body":"Lista de ingredientes completa em toda página de produto, com a função de cada um."},{"title":"Sem crueldade","body":"Não testamos em animais e priorizamos embalagens recicláveis e refis."}],"cta_title":"Comece pelo essencial","cta_body":"Limpar, hidratar, proteger. O resto é ajuste fino.","cta_label":"Ver os kits","cta_href":"/loja?categoria=kits"}'::jsonb),
  ('page_contato', true, '{"eyebrow":"Atendimento","title":"Fale com a gente","intro":"Dúvidas sobre produtos, rotina, pedidos ou trocas? Respondemos em até um dia útil.","show_form":true}'::jsonb)
on conflict (section) do nothing;
